apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: nginx-deploy-patch.yaml
    target:
      kind: Deployment
      name: nginx-deployment

# No secretGenerator: reference the existing secret in your manifests
# Add custom configurations if needed
