apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  template:
    spec:
      containers:
        - name: nginx-container
          image: ghcr.io/nh-homelab/reverse-proxy:latest
          envFrom:
            - secretRef:
                name: proxy-config-secret
