apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  template:
    spec:
      containers:
        - name: nginx-container
          image: nginx:local-test # Use your locally built image tag
          envFrom:
            - configMapRef:
                name: nginx-env
