apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx-container
        image: nginx:latest
        volumeMounts:
        - name: nginx-config-files
          mountPath: /etc/nginx
        - name: nginx-services
          mountPath: /etc/nginx/conf.d
        - name: nginx-html
          mountPath: /usr/share/nginx/html
      volumes:
      - name: nginx-config-files
        configMap:
          name: nginx-config-files
      - name: nginx-html
        configMap:
          name: nginx-html
      - name: nginx-services
        configMap:
          name: nginx-services